set(SOURCE_FILES
	src/glm.hpp
	src/guid.hpp
	src/half.hpp
	src/main.cpp
	src/path.hpp
	src/types.hpp
	src/content/pooled.cpp
	src/content/pooled.hpp
	src/content/Registry.cpp
	src/content/Registry.hpp
	src/core/app_info.cpp
	src/core/app_info.hpp
	src/core/Component.cpp
	src/core/Component.hpp
	src/core/ComponentModule.hpp
	src/core/component_registry.cpp
	src/core/component_registry.hpp
	src/core/Engine.cpp
	src/core/Engine.hpp
	src/core/Entity.cpp
	src/core/Entity.hpp
	src/core/NamedObject.cpp
	src/core/NamedObject.hpp
	src/core/Object.cpp
	src/core/Object.hpp
	src/core/ObjectRegistry.cpp
	src/core/ObjectRegistry.hpp
	src/core/object_pointers.cpp
	src/core/object_pointers.hpp
	src/core/Scene.cpp
	src/core/Scene.hpp
	src/core/Transform.cpp
	src/core/Transform.hpp
	src/core/type_registry.cpp
	src/core/type_registry.hpp
	src/graphics/Buffer.hpp
	src/graphics/Camera.cpp
	src/graphics/Camera.hpp
	src/graphics/Drawable.hpp
	src/graphics/Effect.cpp
	src/graphics/Effect.hpp
	src/graphics/FrameBuffer.cpp
	src/graphics/FrameBuffer.hpp
	src/graphics/gl_types.hpp
	src/graphics/ImageEffect.cpp
	src/graphics/ImageEffect.hpp
	src/graphics/Light.cpp
	src/graphics/Light.hpp
	src/graphics/Material.cpp
	src/graphics/Material.hpp
	src/graphics/Mesh.cpp
	src/graphics/Mesh.hpp
	src/graphics/MeshRenderer.cpp
	src/graphics/MeshRenderer.hpp
	src/graphics/RenderBuffer.cpp
	src/graphics/RenderBuffer.hpp
	src/graphics/RenderEngine.cpp
	src/graphics/RenderEngine.hpp
	src/graphics/Renderer.cpp
	src/graphics/Renderer.hpp
	src/graphics/RenderState.cpp
	src/graphics/RenderState.hpp
	src/graphics/RenderTarget.hpp
	src/graphics/SimpleImageEffect.cpp
	src/graphics/SimpleImageEffect.hpp
	src/graphics/shader/set_uniform.hpp
	src/graphics/shader/Shader.cpp
	src/graphics/shader/Shader.hpp
	src/graphics/shader/ShaderProgram.cpp
	src/graphics/shader/ShaderProgram.hpp
	src/graphics/shader/shader_preprocessor.cpp
	src/graphics/shader/shader_preprocessor.hpp
	src/graphics/shader/shader_property.cpp
	src/graphics/shader/shader_property.hpp
	src/graphics/shader/uniform_id.hpp
	src/graphics/texture/pixel_format_helper.cpp
	src/graphics/texture/pixel_format_helper.hpp
	src/graphics/texture/pixel_types.hpp
	src/graphics/texture/RenderTexture.cpp
	src/graphics/texture/RenderTexture.hpp
	src/graphics/texture/Texture.hpp
	src/graphics/texture/Texture2D.cpp
	src/graphics/texture/Texture2D.hpp
	src/graphics/texture/texture_unit_manager.cpp
	src/graphics/texture/texture_unit_manager.hpp
	src/input/Input.cpp
	src/input/Input.hpp
	src/input/keys.cpp
	src/input/keys.hpp
	src/logging/log.hpp
	src/logging/module_logger.cpp
	src/logging/module_logger.hpp
	src/logging/setup.cpp
	src/logging/setup.hpp
	src/scripting/Behaviour.cpp
	src/scripting/Behaviour.hpp
	src/scripting/class_registry.cpp
	src/scripting/class_registry.hpp
	src/scripting/Environment.cpp
	src/scripting/Environment.hpp
	src/scripting/json_to_lua.cpp
	src/scripting/json_to_lua.hpp
	src/scripting/utility.cpp
	src/scripting/utility.hpp
	src/util/bounds.hpp
	src/util/import.hpp
	src/util/intersection_tests.cpp
	src/util/intersection_tests.hpp
	src/util/json_initializable.hpp
	src/util/json_interpreter.hpp
	src/util/json_utils.cpp
	src/util/json_utils.hpp
	src/util/property_interpreter.hpp
	src/util/random.cpp
	src/util/random.hpp
	src/util/singleton.hpp
)

set(CMAKE_FILES
	cmake/add_boost.cmake
	cmake/external_libs.cmake
	cmake/source_files.cmake
)
source_group("CMake Files" FILES ${CMAKE_FILES})

set(OBJECT_FILES
	content/effects/effect-deferred_light.json
	content/effects/effect-diffuse.json
	content/effects/effect-fxaa.json
	content/effects/effect-pbr_m.json
	content/effects/effect-pbr_mn.json
	content/effects/effect-pbr_s.json
	content/effects/effect-pbr_sc.json
	content/effects/effect-pbr_sn.json
	content/effects/effect-pbr_snc.json
	content/effects/effect-terrain.json
	content/effects/effect-unlit.json
	content/materials/brick.json
	content/materials/debug.json
	content/materials/fxaa.json
	content/materials/mat_barrel_01.json
	content/materials/mat_boardwalk_01.json
	content/materials/mat_boat_01.json
	content/materials/mat_boat_scaffold_01.json
	content/materials/mat_boulder_01.json
	content/materials/mat_bucket_01.json
	content/materials/mat_building_01.json
	content/materials/mat_building_01_darker.json
	content/materials/mat_building_02.json
	content/materials/mat_building_02_darker.json
	content/materials/mat_build_village_fence_01.json
	content/materials/mat_crane_01.json
	content/materials/mat_crane_02.json
	content/materials/mat_dragonhead_01.json
	content/materials/mat_dragonhead_01_darker.json
	content/materials/mat_fence_02.json
	content/materials/mat_fish_01.json
	content/materials/mat_foliage_01.json
	content/materials/mat_fx_water_01.json
	content/materials/mat_gate_01.json
	content/materials/mat_gate_02.json
	content/materials/mat_logpile_01.json
	content/materials/mat_menhir_01.json
	content/materials/mat_plank_01.json
	content/materials/mat_roofbeams_01.json
	content/materials/mat_rune_01.json
	content/materials/mat_shield_01.json
	content/materials/mat_shield_02.json
	content/materials/mat_shield_03.json
	content/materials/mat_skull_01.json
	content/materials/mat_skull_02.json
	content/materials/mat_strawroof_01.json
	content/materials/mat_strawroof_cutout_01.json
	content/materials/mat_sword_shovel_halberd_01.json
	content/materials/mat_terrain_far_01.json
	content/materials/mat_terrain_near_01.json
	content/materials/mat_terrain_near_02.json
	content/materials/mat_torch_01.json
	content/materials/mat_tower_01.json
	content/materials/mat_tower_02.json
	content/materials/mat_tower_03.json
	content/materials/steel.json
	content/scenes/scene-test.json
	content/scenes/The_Viking_Village.json
)
source_group("Object Files" FILES ${OBJECT_FILES})

set(SHADER_FILES
	content/shaders/common/gbuffer.glh
	content/shaders/common/lighting.glh
	content/shaders/common/uniforms.glh
	content/shaders/common/uniforms_img.glh
	content/shaders/common/utils.glh
	content/shaders/common/vertex_input.glh
	content/shaders/common/vertex_input_img.glh
	content/shaders/common/vertex_output.glh
	content/shaders/common/vertex_transform.glh
	content/shaders/diffuse/diffuse.frag.glsl
	content/shaders/diffuse/diffuse.vert.glsl
	content/shaders/diffuse/diffuse_common.glh
	content/shaders/fxaa/fxaa.frag.glsl
	content/shaders/fxaa/fxaa.vert.glsl
	content/shaders/fxaa/fxaa3_11.glh
	content/shaders/fxaa/fxaa_common.glh
	content/shaders/fxaa/fxaa_prepass.frag.glsl
	content/shaders/pbr/pbr_brdf.glh
	content/shaders/pbr/pbr_data.glh
	content/shaders/pbr/pbr_gbuf.glh
	content/shaders/pbr/pbr_input.glh
	content/shaders/pbr/deferred/pbr_deferred_frag.glh
	content/shaders/pbr/deferred/pbr_deferred_m.frag.glsl
	content/shaders/pbr/deferred/pbr_deferred_mn.frag.glsl
	content/shaders/pbr/deferred/pbr_deferred_s.frag.glsl
	content/shaders/pbr/deferred/pbr_deferred_sc.frag.glsl
	content/shaders/pbr/deferred/pbr_deferred_sn.frag.glsl
	content/shaders/pbr/deferred/pbr_deferred_snc.frag.glsl
	content/shaders/pbr/deferred_light/pbr_ambient.frag.glsl
	content/shaders/pbr/deferred_light/pbr_ambient.vert.glsl
	content/shaders/pbr/deferred_light/pbr_ambient_common.glh
	content/shaders/pbr/deferred_light/pbr_defdbg.frag.glsl
	content/shaders/pbr/deferred_light/pbr_light.frag.glsl
	content/shaders/pbr/deferred_light/pbr_light.vert.glsl
	content/shaders/pbr/deferred_light/pbr_light_common.glh
	content/shaders/pbr/forward/pbr_forward_frag.glh
	content/shaders/pbr/forward/pbr_forward_m.frag.glsl
	content/shaders/pbr/forward/pbr_forward_mn.frag.glsl
	content/shaders/pbr/forward/pbr_forward_s.frag.glsl
	content/shaders/pbr/forward/pbr_forward_sc.frag.glsl
	content/shaders/pbr/forward/pbr_forward_sn.frag.glsl
	content/shaders/pbr/forward/pbr_forward_snc.frag.glsl
	content/shaders/std/std_deferred.vert.glsl
	content/shaders/std/std_forward.vert.glsl
	content/shaders/terrain/terrain_deferred.frag.glsl
	content/shaders/terrain/terrain_forward.frag.glsl
	content/shaders/terrain/terrain_input.glh
	content/shaders/unlit/unlit.frag.glsl
	content/shaders/unlit/unlit.vert.glsl
	content/shaders/unlit/unlit_common.glh
)
source_group("Shader Files" FILES ${SHADER_FILES})

set(IMAGE_FILES
	content/textures/build_boat_01_a.tif
	content/textures/build_boat_01_n.tif
	content/textures/build_boat_01_sg.tif
	content/textures/build_boat_02_a.tif
	content/textures/build_boat_02_n.tif
	content/textures/build_building_01_a.tif
	content/textures/build_building_01_n.tif
	content/textures/build_building_01_sg.tif
	content/textures/build_building_02_a.tif
	content/textures/build_building_02_n.tif
	content/textures/build_building_02_sg.tif
	content/textures/build_crane_01_a.tif
	content/textures/build_crane_01_n.tif
	content/textures/build_crane_02_n.tif
	content/textures/build_crane_02_sg.tif
	content/textures/build_dragonhead_01_a.tif
	content/textures/build_dragonhead_01_n.tif
	content/textures/build_gate_01_a.tif
	content/textures/build_gate_01_n.tif
	content/textures/build_gate_02_a.tif
	content/textures/build_gate_02_n.tif
	content/textures/build_gate_02_sg.tif
	content/textures/build_strawroofs_01_a.tif
	content/textures/build_strawroofs_01_n.tif
	content/textures/build_tower_01_a.tif
	content/textures/build_tower_01_n.tif
	content/textures/build_tower_01_SG.tif
	content/textures/build_tower_02_a.tif
	content/textures/build_tower_02_n.tif
	content/textures/build_tower_03_a.tif
	content/textures/build_tower_03_n.tif
	content/textures/build_tower_03_sg.tif
	content/textures/build_village_fence_01_a.tif
	content/textures/build_village_fence_01_n.tif
	content/textures/build_village_fence_01_sg.tif
	content/textures/prop_barrel_01_a.tif
	content/textures/prop_barrel_01_n.tif
	content/textures/prop_barrel_01_sg.tif
	content/textures/prop_boardwalk_01_d.tif
	content/textures/prop_boardwalk_01_n.tif
	content/textures/prop_boardwalk_01_sg.tif
	content/textures/prop_boulder_01_d.tif
	content/textures/prop_boulder_01_n.tif
	content/textures/prop_bucket_01_a.tif
	content/textures/prop_bucket_01_n.tif
	content/textures/prop_bucket_01_sg.tif
	content/textures/prop_fence_02_a.tif
	content/textures/prop_fence_02_n.tif
	content/textures/prop_fish_01_d.tif
	content/textures/prop_fish_01_n.tif
	content/textures/prop_fish_01_sg.tif
	content/textures/prop_logpile_01_d.tif
	content/textures/prop_menhir_01_d.tif
	content/textures/prop_menhir_01_n.tif
	content/textures/prop_rune_01_d.tif
	content/textures/prop_rune_01_n.tif
	content/textures/prop_rune_01_sg.tif
	content/textures/prop_shield_01_d.tif
	content/textures/prop_shield_01_n.tif
	content/textures/prop_shield_01_sg.tif
	content/textures/prop_shield_02_d.tif
	content/textures/prop_shield_03_a.tif
	content/textures/prop_shield_03_n.tif
	content/textures/prop_shield_03_sg.tif
	content/textures/prop_skull_01_d.tif
	content/textures/prop_skull_01_n.tif
	content/textures/prop_skull_01_sg.tif
	content/textures/prop_sword_shovel_halberd_01_d.tif
	content/textures/prop_sword_shovel_halberd_01_n.tif
	content/textures/prop_sword_shovel_halberd_01_sg.tif
	content/textures/terrain_01_m.tif
	content/textures/terrain_01_n.tif
	content/textures/terrain_01_o.tif
	content/textures/terrain_far_01_a2.tif
	content/textures/terrain_far_01_sg.tif
	content/textures/terrain_grass_01_a.tif
	content/textures/terrain_grass_01_n.tif
	content/textures/terrain_grass_01_sg.tif
	content/textures/terrain_mudslide_01_a.tif
	content/textures/terrain_mudslide_01_n.tif
	content/textures/terrain_mudslide_01_sg.tif
	content/textures/terrain_wetmud_01_a.tif
	content/textures/terrain_wetmud_01_n.tif
	content/textures/terrain_wetmud_01_sg.tif
	content/textures/veg_foliage_01_d.tif
	content/textures/wood_tiled_02_a.tif
	content/textures/wood_tiled_02_n.tif
	content/textures/brick/brick_albedo.jpg
	content/textures/brick/brick_normal.jpg
	content/textures/steel/steel_albedo.png
	content/textures/steel/steel_metallic.png
	content/textures/steel/steel_normal.png
)
source_group("Image Files" FILES ${IMAGE_FILES})

set(MODEL_FILES
	content/meshes/build_barracks_01.fbx
	content/meshes/build_barracks_single_01.fbx
	content/meshes/build_bighouse_01.fbx
	content/meshes/build_bighouse_02.FBX
	content/meshes/build_big_storage_01.fbx
	content/meshes/build_blacksmith_01.fbx
	content/meshes/build_boat_01.FBX
	content/meshes/build_crane_01.FBX
	content/meshes/build_gate_01.fbx
	content/meshes/build_small_house_01.FBX
	content/meshes/build_small_house_straw_roof_01.FBX
	content/meshes/build_small_house_tall_roof_01.FBX
	content/meshes/build_storage_01.fbx
	content/meshes/build_tower_01.FBX
	content/meshes/build_wall_corner_01.FBX
	content/meshes/build_wall_panel_01.FBX
	content/meshes/cube.blend
	content/meshes/ocean_plane.FBX
	content/meshes/prop_barrels_01.fbx
	content/meshes/prop_barrels_02.fbx
	content/meshes/prop_barrel_01.fbx
	content/meshes/prop_boardwalk_01.FBX
	content/meshes/prop_boulder_01.fbx
	content/meshes/prop_boulder_02.fbx
	content/meshes/prop_buckets_01.fbx
	content/meshes/prop_bucket_01.fbx
	content/meshes/prop_fence_01.fbx
	content/meshes/prop_fence_01_double.fbx
	content/meshes/prop_fence_01_tripple.fbx
	content/meshes/prop_fence_02.FBX
	content/meshes/prop_fence_02_double.fbx
	content/meshes/prop_fence_02_quad.fbx
	content/meshes/prop_fish_01.fbx
	content/meshes/prop_halberd_01.fbx
	content/meshes/prop_logpile_01.fbx
	content/meshes/prop_menhir_01.fbx
	content/meshes/prop_pillar_03.fbx
	content/meshes/prop_pillar_04.fbx
	content/meshes/prop_pillar_05.fbx
	content/meshes/prop_pillar_06.fbx
	content/meshes/prop_plankpath_01.FBX
	content/meshes/prop_plankpile_01.fbx
	content/meshes/prop_plankpile_02.fbx
	content/meshes/prop_plankpile_03.fbx
	content/meshes/prop_plank_01.fbx
	content/meshes/prop_plank_02.fbx
	content/meshes/prop_plank_03.fbx
	content/meshes/prop_rune_01.fbx
	content/meshes/prop_scaffold_01.fbx
	content/meshes/prop_shed_01.fbx
	content/meshes/prop_shed_02.fbx
	content/meshes/prop_shield_01.fbx
	content/meshes/prop_shovel_01.fbx
	content/meshes/prop_skull_01.fbx
	content/meshes/prop_sword_01.fbx
	content/meshes/prop_torch_01.fbx
	content/meshes/prop_wall_logs_04.FBX
	content/meshes/terrain_01.fbx
	content/meshes/veg_clovers_01.fbx
	content/meshes/veg_clovers_purple_01.fbx
	content/meshes/veg_clovers_white_01.fbx
	content/meshes/veg_plant_02.fbx
)
source_group("Model Files" FILES ${MODEL_FILES})

set(SCRIPT_FILES
	content/scripts/BounceInBox.lua
	content/scripts/DayNightController.lua
	content/scripts/DebugControls.lua
	content/scripts/FlyCamera.lua
	content/scripts/LightingTest.lua
	content/scripts/LightSwitch.lua
	content/scripts/Object.lua
	content/scripts/Test.lua
	content/scripts/xmath/aabb.lua
	content/scripts/xmath/color.lua
	content/scripts/xmath/init.lua
	content/scripts/xmath/quat.lua
	content/scripts/xmath/random.lua
	content/scripts/xmath/struct.lua
	content/scripts/xmath/vec2.lua
	content/scripts/xmath/vec3.lua
	content/scripts/xmath/vec4.lua
)
source_group("Script Files" FILES ${SCRIPT_FILES})

